
// === === === === === === Mixin Path Start === === === === === ===

repositories {
    maven {
        url 'https://jitpack.io'
    }
}

def unimixinsVersion = "0.3.1"

dependencies {
    implementation("com.github.LegacyModdingMC.UniMixins:unimixins-all-1.7.10:$unimixinsVersion:dev")
    annotationProcessor("com.github.LegacyModdingMC.UniMixins:unimixins-all-1.7.10:$unimixinsVersion:dev")
}

runClient {
    args("--tweakClass", "org.spongepowered.asm.launch.MixinTweaker")
}

runServer {
    args("--tweakClass", "org.spongepowered.asm.launch.MixinTweaker")
}

def outSrgFile = "${tasks.compileJava.temporaryDir}/outSrg.srg"
def outRefMapFile = "${tasks.compileJava.temporaryDir}/mixins.${modId}.refmap.json"

jar {
    manifest {
        attributes (
                'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
                'MixinConfigs': "mixins.${modId}.json",
                'ForceLoadAsMod': 'true',
                'FMLCorePluginContainsFMLMod': 'true',
        )
    }

    from outRefMapFile;
}

tasks.compileJava.options.compilerArgs += ["-AreobfSrgFile=${tasks.reobf.srg}",
                                           "-AoutSrgFile=${outSrgFile}",
                                           "-AoutRefMapFile=${outRefMapFile}"];

reobf {
    addExtraSrgFile outSrgFile
}

// === === === === === === Mixin Path End === === === === === ===
